### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Victor239** [GnuCash-Pocket/gnucash-android#129]
Having this option would really help my eyes :) thanks for reviving this app!

**Comment by eozalp** [comment]
Exactly. By the why Moshe Waisberg. Thank you to revive this most wonderful piece of software. You are working on an amazing project. You know it. Appreciated.

**Comment by dmaroulidis** [comment]
Hi! Great addition, but could we just have a toggle in the settings for dark mode. I've gotten quite used to the previous theme and I can't read that well with white text on grey background. 

I also like having the rest of the system in dark mode so changing the setting systemwide isn't an option. Thank you!!!

**Comment by djbrown** [comment]
@dmaroulidis do the subsequent changes on #194 meet your requirements?

**Comment by dmaroulidis** [comment]
@djbrown No they don't. I don't see a setting in app settings for toggling dark mode. Did you add that or are you referring to changing the text color?

**Comment by djbrown** [comment]
@dmaroulidis that should've been implemented with #164. If it's missing we might have a bug/- regression. I'm not up to date with the latest contributions though, but @pnemonic78 probably knows.

**Comment by Victor239** [comment]
Its dark themed for me with my Android settings set to dark mode all my apps.
