### ISSUE TITLE
Allow adding multiple accounts to a transaction

### ISSUE THREAD

**Issue by joshpetit** [GnuCash-Pocket/gnucash-android#131]
Currently, you can only add one account associated with a transaction. A use case I would like to do:

    Add a transaction to income that adds $100
    Add an entry to that transaction that takes out $20 for taxes
    Add an entry to that transaction that adds $80 to my checking account

Would this be something you find worth adding to the roadmap? Thank you

**Comment by Kaligula0** [comment]
You can do it. Use the split ("fork arrow" icon).

**Comment by joshpetit** [comment]
Ah you're right. Thanks.

**Comment by Kaligula0** [comment]
Np.
