### ISSUE TITLE
In qif exported file S and $ field are missing

### ISSUE THREAD

**Issue by albelixpd** [GnuCash-Pocket/gnucash-android#133]
## Steps to reproduce the behaviour
tap menu, export, select qif format
select date from
export

## Expected behaviour
!Account
NUscite:Regali
^
!Type:Cash
D2024/5/24
Ptest
Mnota
SAttività:Attività correnti:Liquidità
$12.00
^

## Actual behaviour
!Account
NUscite:Regali
^
!Type:Cash
D2024/5/24
Ptest
Mnota
^

## Software specifications
* GnuCash Android version: 2.5.1
* System Android version: OxigenOS 14
* Device type: Oneplus 10pro
* S.O. language: Italian/ euro

**Comment by pnemonic78** [comment]
@albelixpd Please attach "edit transaction" and "edit splits" screenshots of the problematic transaction.

**Comment by albelixpd** [comment]
![Screenshot_2024-05-28-08-16-11-91_1ec4865c375114067b8db8763eefe95a](https://github.com/GnuCash-Pocket/gnucash-android/assets/50218771/8c34e388-2a34-44fe-b60d-29c039eb74d4)
![Screenshot_2024-05-28-08-16-52-36_1ec4865c375114067b8db8763eefe95a](https://github.com/GnuCash-Pocket/gnucash-android/assets/50218771/1f010775-cb45-40f2-8a0b-868664de0018)
![Screenshot_2024-05-28-08-19-18-54_1ec4865c375114067b8db8763eefe95a](https://github.com/GnuCash-Pocket/gnucash-android/assets/50218771/3bd333db-d1eb-4ce1-9049-deaf869b6877)
![Screenshot_2024-05-28-08-20-41-97_1ec4865c375114067b8db8763eefe95a](https://github.com/GnuCash-Pocket/gnucash-android/assets/50218771/79e92c45-27ff-490e-84b1-efc6712d5d7d)

**Comment by albelixpd** [comment]
`
!Account
NAttività:Aperte:Liquidità
^
!Type:Cash
D2024/5/28
PTest
MTreno per Roma
^
`

**Comment by pnemonic78** [comment]
Was introduced as part of fix to issue #99

**Comment by djbrown** [comment]
@pnemonic78 how was this fixed? there is no referencing pr. only the introducing #99.
