### ISSUE TITLE
Convertion Rate asked for EUR to EUR for each transaction

### ISSUE THREAD

**Issue by nodje** [GnuCash-Pocket/gnucash-android#157]
This is my first use of Pocket, I have using it's predecessor for years.

## Steps to reproduce the behaviour
I imported accounts from my pc instance (many accounts in many currencies)
Started to input tx EUR to EUR

## Expected behaviour
No conversion rate asked :)

## Actual behaviour
Conversion rate asked

## Software specifications
* GnuCash Android version: 2.5.1
*  System Android version: 14
* Device type: Pixel8

QIF export to my PC instance worked flawlessly though, but inputing tx is just too annoying with the additional rate dialog

**Comment by pnemonic78** [comment]
fixed in commit 2b06f379e99132562f811a80b3809eede0419abd

**Comment by djbrown** [comment]
2b06f37 "does not belong to any branch on this repository"
@pnemonic78 has this been merged yet?
the message is the same as b1eb324
but that was merged many weeks ago in #96 and has different changes

**Comment by djbrown** [comment]
never mind, I just found it in #155
