### ISSUE TITLE
In reports there is extra text and graph behind

### ISSUE THREAD

**Issue by eozalp** [GnuCash-Pocket/gnucash-android#159]
## Steps to reproduce the behaviour
1. Menu-> reports.
2. Line Charts button
3. Pie Chart in dropdown
4. [back button]

Up to graphics there is graphics and text hidden behind title.

## Expected behaviour

No text or graph behind title after back button

## Actual behaviour

There is extra text and graphics behind.

## Software specifications
* GnuCash Android version: 2.5.1
* System Android version: 14
* Device type: Samsung Galaxy 13 ultra

## Suggested Resolution

I don't know.
![Screenshot_20240622_195423_GnuCash](https://github.com/GnuCash-Pocket/gnucash-android/assets/25224036/7407eb95-9c57-4b55-8411-3063fdf02163)

**Comment by pnemonic78** [comment]
fixed in commit ddc66ede37762000253daa178cf03110fa3b73a0

**Comment by djbrown** [comment]
ddc66ed "does not belong to any branch on this repository"
@pnemonic78 will you create a pull request for this?
I couldn't find any related commits/prs in this repo.

**Comment by djbrown** [comment]
never mind, I just found it in #153
