### ISSUE TITLE
Upgrade project setup to Android API Level 33

### ISSUE THREAD

**Issue by djbrown** [GnuCash-Pocket/gnucash-android#17]
Mostly automated by Android Studio migration service

**Comment by XilinJia** [comment]
Up to this commit, I updated the original gnucash-android to Androidx and SDK 33.  All codes still in Java.
https://github.com/XilinJia/gnucash-android-kotlin/commit/2f1728496da8d5ac728eb09a942eb1e5dcd0b814

**Comment by Kaligula0** [comment]
Is this connected to https://github.com/GnuCash-Pocket/gnucash-android/pull/55?
