### ISSUE TITLE
Exporting to CSV writes a 0 byte file, 'There are no transactions available to export' message

### ISSUE THREAD

**Issue by Apteryks** [GnuCash-Pocket/gnucash-android#190]
## Steps to reproduce the behaviour
With my GnuCash file loaded:
1. Select 'Export...' from the burger menu
2. Select SINCE date or All time (doesn't matter)
3. Export 'Save As...', with 'Comma-separated values'
4. Touch `Export` button

## Expected behaviour

Creates a .csv file with transactions in.

## Actual behaviour

Prints a `There are no transactions available to export` message and writes a 0 byte (empty) file.

## Software specifications
* GnuCash Android version: 2.5.2
* System Android version: 7.0
* Device type: Tablet (Samsung Galaxy Tab S2)

**Comment by Apteryks** [comment]
Seems to be the same underlying problem as reported in https://github.com/GnuCash-Pocket/gnucash-android/issues/98

**Comment by BaumiCoder** [comment]
The error appears also for the Quicken Interchange Format (qif).

**Comment by pnemonic78** [comment]
Duplicate of issue #140  ?

**Comment by pnemonic78** [comment]
Duplicate of issue #98 ?

**Comment by Apteryks** [comment]
Yes, I think so.
