### ISSUE TITLE
Create CI-Build with GitHub Actions

### ISSUE THREAD

**Issue by djbrown** [GnuCash-Pocket/gnucash-android#6]
* Install Dependencies
* Run Unit Tests
* optional: Check Code Formatting
* Analyse Code Quality

Should run on each push for every branch and pull request
Should use as much caching as possible to get fast results

**Comment by djbrown** [comment]
I implemented a rudimentary CI Pipeline which essentially just runs `./gradlew build` see https://github.com/GnuCash-Pocket/gnucash-android/actions
It takes ~15min though. Is that comparable to your local setup? Maybe we can speed it up with caching or running smaller steps in parallel? I don't know all the Android specific gradle tasks though.

@XilinJia do you see any potential to speed up performance ?

**Comment by XilinJia** [comment]
I don't know too much of what's going on behind the scenes with the actions.  Suppose it goes similarly as building locally, a couple things could slow down the build.

1) the first build needs to download all the dependencies, so subsequent build will improve.
2) `./gradlew build` actually builds every variant and flavors of the project.  We have development, beta, production, debug, release in this project.  (Do we need CI to do all of these?)
3) if you just have one CPU and a little memory.  This can be configured in gradle.properties for local builds, but I am not sure if we should configure it for the project by default (for CI purpose) as it more pertains to each developer's choice.

Considering the above, 15 minutes might not be abnormal.

To improve CI, aside from minding about 2) above, perhaps we can try gradle-build-action as it's supposed to be more efficient than plain CI pipeline.

**Comment by djbrown** [comment]
For 1) I'll have a loot the https://github.com/marketplace/actions/gradle-build-action

For 2) I suggest running only unit tests of flavor development and variant debug

For 3) I looked at [GitHub Runners Docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). we could configure up to 2 CPUs and 7GB RAM

**Comment by djbrown** [comment]
The CI-Build is now down to 3min :)
* [Increase gradle memory to 6GB](https://github.com/GnuCash-Pocket/gnucash-android/commit/43858a2bff201ba3f6a3c0167c4098420afd8eff)
* [use gradle-build-action for caching](https://github.com/GnuCash-Pocket/gnucash-android/commit/d0aa342c50a8f1567c1253696855a2105dc4a527)
* [only run dev-debug Unit Tests](https://github.com/GnuCash-Pocket/gnucash-android/commit/a51edf0e4e535760747cc4f0739ec4cfe14d575a)

**Comment by JeanGarf** [comment]
Good job !
