### ISSUE TITLE
migrate from butterknife to Jetpack view bindings

### ISSUE THREAD

**Issue by hades** [GnuCash-Pocket/gnucash-android#73]
The code currently uses Butterknife[1] which is deprecated in favour of view bindings[2].

There are 27 files that use view binding:

- [ ] app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/budget/BudgetAmountEditorFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/budget/BudgetDetailFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/budget/BudgetFormFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/budget/BudgetListFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/export/ExportFormFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/ReportsOverviewFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/barchart/StackedBarChartFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/linechart/CashFlowLineChartFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/piechart/PieChartFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/report/sheet/BalanceSheetFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/settings/PreferenceActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/transaction/TransactionDetailActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/transaction/TransactionsActivity.java
- [ ] app/src/main/java/org/gnucash/android/ui/transaction/TransactionsListFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/util/dialog/DateRangePickerDialogFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/wizard/CurrencySelectFragment.java
- [ ] app/src/main/java/org/gnucash/android/ui/wizard/FirstRunWizardActivity.java

[1] https://github.com/JakeWharton/butterknife
[2] https://developer.android.com/topic/libraries/view-binding#kts

**Comment by hades** [comment]
If no one has any objections, I can work on migrating these classes.

**Comment by djbrown** [comment]
Seems reasonable, according to the readme it's deprecated.
Not sure about how big of an impact that will have and conflict potential with pending/incoming changes from @pnemonic78.
But please feel free to work in it 👍🏾
