### ISSUE TITLE
When enteribg transaction komma ist not working as decimal seperator

### ISSUE THREAD

**Issue by seanomat** [GnuCash-Pocket/gnucash-android#88]
## Steps to reproduce the behaviour
1. 
When entering a transaction with decimal and you press the komma in the integrated Keyboard, it does not appear in the amount field. 
When I press the period instead, it does appear and is converted to a komma, once the transaction is submitted.

## Expected behaviour
Komma to appear and stay

## Actual behaviour
Komma is ignored.
Period ist converted to komma

## Software specifications
* GnuCash Android version: 2.5.1
* System Android version: 14
* Device type: Pixel 6a

**Comment by Kaligula0** [comment]
Looks like a locale issue.
What language is your phone set to? What region/country?

**Comment by Kaligula0** [comment]
Possibly linked to #37?

**Comment by seanomat** [comment]
Device is set to German/Germany

**Comment by seanomat** [comment]
Seems to have been solved with the recent update
